spring:
  datasource:
    username: demo2
    password: demo2
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/demo2
    driver-class-name: com.mysql.jdbc.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update