spring:
  datasource:
    username: demo2
    password: demo2
    url: jdbc:h2:mem:demo2
    driver-class-name: org.h2.Driver
  h2:
    console.enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
